# Generated by Django 5.2 on 2025-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0002_appuser_loaned_alter_appuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
