# Generated by Django 5.2 on 2025-04-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=30)),
                ('Publisher', models.CharField(max_length=40)),
                ('Year_Published', models.DateTimeField()),
            ],
        ),
    ]
