# Generated by Django 5.2 on 2025-04-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Year_Published',
            new_name='year_published',
        ),
    ]
