# Generated by Django 5.2 on 2025-04-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0003_book_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
    ]
